pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Agent {
    /// The ID of the agent.
    #[serde(default)]
    pub id: String,
    /// The name of the agent.
    #[serde(default)]
    pub name: String,
    /// The phone number that the agent uses to accept calls. `null` if the agent is not associated with a phone number, in which can the agent can be used via WebSockets. This field is deprecated. Use `phone_numbers` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    /// Array of phone numbers that the agent uses to accept phone calls.
    #[serde(default)]
    pub phone_numbers: Vec<String>,
    /// The project the agent belongs to.
    #[serde(default)]
    pub project: AgentProject,
    /// The timezone of the agent. Used to format system variables like `{{system_time}}`.
    #[serde(default)]
    pub timezone: String,
    /// The voice ID of the agent.
    #[serde(default)]
    pub voice_id: String,
    /// The audio format of the agent. If the agent has a phone number, the audio format will be `mulaw_8000`.
    pub audio_format: AgentAudioFormat,
    /// The audio speed of the agent. Must be a multiple of 0.1.
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers")]
    pub audio_speed: f64,
    /// The background noise level of the agent. Must be between 0 and 1.
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers")]
    pub background_noise_level: f64,
    /// The background noise type. Can be "office", "call-center", "coffee-shop", or null.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background_noise: Option<AgentBackgroundNoise>,
    /// When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    #[serde(default)]
    pub generate_welcome_message: bool,
    /// When `false`, the welcome message will not be interruptible by the user.
    #[serde(default)]
    pub is_welcome_message_interruptible: bool,
    /// Number of seconds of inactivity before the conversation WebSocket is closed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub websocket_timeout_sec: Option<i64>,
    /// Message to play when the conversation starts. Ignored when `generate_welcome_message` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<String>,
    /// Instructions for the conversation.
    #[serde(default)]
    pub system_prompt: String,
    /// Template variables that the agent can use in the welcome message and the system prompt.
    #[serde(default)]
    pub template_variables: HashMap<String, AgentTemplateVariablesValue>,
    /// List of tools available to the agent.
    #[serde(default)]
    pub tools: Vec<AgentToolsItem>,
    /// Configuration overrides for built-in tools, keyed by built-in tool ID.
    #[serde(default)]
    pub built_in_tool_configs: BuiltInToolConfigs,
    /// Tasks for the agent to complete during the conversation.
    #[serde(default)]
    pub tasks: Vec<Task>,
    /// Whether to have the no-input poke text be generated by AI.
    #[serde(default)]
    pub generate_no_input_poke_text: bool,
    /// Number of seconds of silence before sending a poke message. `null` disables the poke message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_sec: Option<i64>,
    /// The message to send after the specified silence. Ignored when generate_no_input_poke_text is true.
    #[serde(default)]
    pub no_input_poke_text: String,
    /// Seconds of silence before ending the conversation.
    #[serde(default)]
    pub no_input_end_conversation_sec: i64,
    /// ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    pub default_language: LanguageCode,
    /// Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    #[serde(default)]
    pub additional_languages: Vec<LanguageCode>,
    /// Array of ISO 639-1 language codes that the agent should be able to recognize. This field is deprecated. Use `default_language` and `additional_languages` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<LanguageCode>>,
    /// If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    pub multilingual_mode: AgentMultilingualMode,
    /// Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    #[serde(default)]
    pub push_to_talk: bool,
    /// The intelligence level of the agent. `high` uses a more capable model for more complex reasoning, while `standard` is optimized for lower latency.
    pub intelligence_level: AgentIntelligenceLevel,
    /// These words, or short phrases, will be more accurately recognized by the agent.
    #[serde(default)]
    pub boosted_keywords: Vec<String>,
    /// Names of observability integrations enabled for the agent. Each must be one of the supported providers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observability_integrations: Option<Vec<String>>,
    /// Array of `{ word, pronunciation }` entries. Words must be unique.
    #[serde(default)]
    pub pronunciation_dictionary: Vec<AgentPronunciationDictionaryItem>,
    /// Minimum number of words required to interrupt the assistant.
    #[serde(default)]
    pub min_words_to_interrupt: i64,
    /// When not `null`, the agent will call this endpoint to get configuration options.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub configuration_endpoint: Option<AgentConfigurationEndpoint>,
    /// Float between 0.0 and 1.0 representing the percentage of inbound calls handled by Agent. Requires `phone_number` to be set when less than 1.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub inbound_rollout: Option<f64>,
    /// E.164 formatted phone number where non-agent calls will be forwarded. Required when `inbound_rollout < 1.0`, must be `null` when `inbound_rollout = 1.0`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_rollout_forward_phone_number: Option<String>,
    /// Voice activity detection prebuffer duration in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_prebuffer_duration_ms: Option<i64>,
    /// Minimum speech duration for voice activity detection in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_speech_duration_ms: Option<i64>,
    /// Minimum silence duration for voice activity detection in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_silence_duration_ms: Option<i64>,
    /// Voice activity detection threshold.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub vad_threshold: Option<f64>,
    /// When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_redaction: Option<bool>,
    /// The URL-friendly slug of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// When `true`, the assistant emits backchannel cues (e.g. "mm-hmm") while the user is speaking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_assistant_backchannel: Option<bool>,
    /// How aggressively the assistant backchannels, from 0 to 1.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub assistant_backchannel_aggressiveness: Option<f64>,
    /// Third-party integrations enabled for the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub integrations: Option<Vec<AgentIntegration>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_retention_policy: Option<DataRetentionPolicy>,
}

impl Agent {
    pub fn builder() -> AgentBuilder {
        <AgentBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct AgentBuilder {
    id: Option<String>,
    name: Option<String>,
    phone_number: Option<String>,
    phone_numbers: Option<Vec<String>>,
    project: Option<AgentProject>,
    timezone: Option<String>,
    voice_id: Option<String>,
    audio_format: Option<AgentAudioFormat>,
    audio_speed: Option<f64>,
    background_noise_level: Option<f64>,
    background_noise: Option<AgentBackgroundNoise>,
    generate_welcome_message: Option<bool>,
    is_welcome_message_interruptible: Option<bool>,
    websocket_timeout_sec: Option<i64>,
    welcome_message: Option<String>,
    system_prompt: Option<String>,
    template_variables: Option<HashMap<String, AgentTemplateVariablesValue>>,
    tools: Option<Vec<AgentToolsItem>>,
    built_in_tool_configs: Option<BuiltInToolConfigs>,
    tasks: Option<Vec<Task>>,
    generate_no_input_poke_text: Option<bool>,
    no_input_poke_sec: Option<i64>,
    no_input_poke_text: Option<String>,
    no_input_end_conversation_sec: Option<i64>,
    default_language: Option<LanguageCode>,
    additional_languages: Option<Vec<LanguageCode>>,
    languages: Option<Vec<LanguageCode>>,
    multilingual_mode: Option<AgentMultilingualMode>,
    push_to_talk: Option<bool>,
    intelligence_level: Option<AgentIntelligenceLevel>,
    boosted_keywords: Option<Vec<String>>,
    observability_integrations: Option<Vec<String>>,
    pronunciation_dictionary: Option<Vec<AgentPronunciationDictionaryItem>>,
    min_words_to_interrupt: Option<i64>,
    configuration_endpoint: Option<AgentConfigurationEndpoint>,
    inbound_rollout: Option<f64>,
    inbound_rollout_forward_phone_number: Option<String>,
    vad_prebuffer_duration_ms: Option<i64>,
    vad_min_speech_duration_ms: Option<i64>,
    vad_min_silence_duration_ms: Option<i64>,
    vad_threshold: Option<f64>,
    enable_redaction: Option<bool>,
    slug: Option<String>,
    enable_assistant_backchannel: Option<bool>,
    assistant_backchannel_aggressiveness: Option<f64>,
    integrations: Option<Vec<AgentIntegration>>,
    data_retention_policy: Option<DataRetentionPolicy>,
}

impl AgentBuilder {
    pub fn id(mut self, value: impl Into<String>) -> Self {
        self.id = Some(value.into());
        self
    }

    pub fn name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    pub fn phone_number(mut self, value: impl Into<String>) -> Self {
        self.phone_number = Some(value.into());
        self
    }

    pub fn phone_numbers(mut self, value: Vec<String>) -> Self {
        self.phone_numbers = Some(value);
        self
    }

    pub fn project(mut self, value: AgentProject) -> Self {
        self.project = Some(value);
        self
    }

    pub fn timezone(mut self, value: impl Into<String>) -> Self {
        self.timezone = Some(value.into());
        self
    }

    pub fn voice_id(mut self, value: impl Into<String>) -> Self {
        self.voice_id = Some(value.into());
        self
    }

    pub fn audio_format(mut self, value: AgentAudioFormat) -> Self {
        self.audio_format = Some(value);
        self
    }

    pub fn audio_speed(mut self, value: f64) -> Self {
        self.audio_speed = Some(value);
        self
    }

    pub fn background_noise_level(mut self, value: f64) -> Self {
        self.background_noise_level = Some(value);
        self
    }

    pub fn background_noise(mut self, value: AgentBackgroundNoise) -> Self {
        self.background_noise = Some(value);
        self
    }

    pub fn generate_welcome_message(mut self, value: bool) -> Self {
        self.generate_welcome_message = Some(value);
        self
    }

    pub fn is_welcome_message_interruptible(mut self, value: bool) -> Self {
        self.is_welcome_message_interruptible = Some(value);
        self
    }

    pub fn websocket_timeout_sec(mut self, value: i64) -> Self {
        self.websocket_timeout_sec = Some(value);
        self
    }

    pub fn welcome_message(mut self, value: impl Into<String>) -> Self {
        self.welcome_message = Some(value.into());
        self
    }

    pub fn system_prompt(mut self, value: impl Into<String>) -> Self {
        self.system_prompt = Some(value.into());
        self
    }

    pub fn template_variables(mut self, value: HashMap<String, AgentTemplateVariablesValue>) -> Self {
        self.template_variables = Some(value);
        self
    }

    pub fn tools(mut self, value: Vec<AgentToolsItem>) -> Self {
        self.tools = Some(value);
        self
    }

    pub fn built_in_tool_configs(mut self, value: BuiltInToolConfigs) -> Self {
        self.built_in_tool_configs = Some(value);
        self
    }

    pub fn tasks(mut self, value: Vec<Task>) -> Self {
        self.tasks = Some(value);
        self
    }

    pub fn generate_no_input_poke_text(mut self, value: bool) -> Self {
        self.generate_no_input_poke_text = Some(value);
        self
    }

    pub fn no_input_poke_sec(mut self, value: i64) -> Self {
        self.no_input_poke_sec = Some(value);
        self
    }

    pub fn no_input_poke_text(mut self, value: impl Into<String>) -> Self {
        self.no_input_poke_text = Some(value.into());
        self
    }

    pub fn no_input_end_conversation_sec(mut self, value: i64) -> Self {
        self.no_input_end_conversation_sec = Some(value);
        self
    }

    pub fn default_language(mut self, value: LanguageCode) -> Self {
        self.default_language = Some(value);
        self
    }

    pub fn additional_languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.additional_languages = Some(value);
        self
    }

    pub fn languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.languages = Some(value);
        self
    }

    pub fn multilingual_mode(mut self, value: AgentMultilingualMode) -> Self {
        self.multilingual_mode = Some(value);
        self
    }

    pub fn push_to_talk(mut self, value: bool) -> Self {
        self.push_to_talk = Some(value);
        self
    }

    pub fn intelligence_level(mut self, value: AgentIntelligenceLevel) -> Self {
        self.intelligence_level = Some(value);
        self
    }

    pub fn boosted_keywords(mut self, value: Vec<String>) -> Self {
        self.boosted_keywords = Some(value);
        self
    }

    pub fn observability_integrations(mut self, value: Vec<String>) -> Self {
        self.observability_integrations = Some(value);
        self
    }

    pub fn pronunciation_dictionary(mut self, value: Vec<AgentPronunciationDictionaryItem>) -> Self {
        self.pronunciation_dictionary = Some(value);
        self
    }

    pub fn min_words_to_interrupt(mut self, value: i64) -> Self {
        self.min_words_to_interrupt = Some(value);
        self
    }

    pub fn configuration_endpoint(mut self, value: AgentConfigurationEndpoint) -> Self {
        self.configuration_endpoint = Some(value);
        self
    }

    pub fn inbound_rollout(mut self, value: f64) -> Self {
        self.inbound_rollout = Some(value);
        self
    }

    pub fn inbound_rollout_forward_phone_number(mut self, value: impl Into<String>) -> Self {
        self.inbound_rollout_forward_phone_number = Some(value.into());
        self
    }

    pub fn vad_prebuffer_duration_ms(mut self, value: i64) -> Self {
        self.vad_prebuffer_duration_ms = Some(value);
        self
    }

    pub fn vad_min_speech_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_speech_duration_ms = Some(value);
        self
    }

    pub fn vad_min_silence_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_silence_duration_ms = Some(value);
        self
    }

    pub fn vad_threshold(mut self, value: f64) -> Self {
        self.vad_threshold = Some(value);
        self
    }

    pub fn enable_redaction(mut self, value: bool) -> Self {
        self.enable_redaction = Some(value);
        self
    }

    pub fn slug(mut self, value: impl Into<String>) -> Self {
        self.slug = Some(value.into());
        self
    }

    pub fn enable_assistant_backchannel(mut self, value: bool) -> Self {
        self.enable_assistant_backchannel = Some(value);
        self
    }

    pub fn assistant_backchannel_aggressiveness(mut self, value: f64) -> Self {
        self.assistant_backchannel_aggressiveness = Some(value);
        self
    }

    pub fn integrations(mut self, value: Vec<AgentIntegration>) -> Self {
        self.integrations = Some(value);
        self
    }

    pub fn data_retention_policy(mut self, value: DataRetentionPolicy) -> Self {
        self.data_retention_policy = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`Agent`].
    /// This method will fail if any of the following fields are not set:
    /// - [`id`](AgentBuilder::id)
    /// - [`name`](AgentBuilder::name)
    /// - [`phone_numbers`](AgentBuilder::phone_numbers)
    /// - [`project`](AgentBuilder::project)
    /// - [`timezone`](AgentBuilder::timezone)
    /// - [`voice_id`](AgentBuilder::voice_id)
    /// - [`audio_format`](AgentBuilder::audio_format)
    /// - [`audio_speed`](AgentBuilder::audio_speed)
    /// - [`background_noise_level`](AgentBuilder::background_noise_level)
    /// - [`generate_welcome_message`](AgentBuilder::generate_welcome_message)
    /// - [`is_welcome_message_interruptible`](AgentBuilder::is_welcome_message_interruptible)
    /// - [`system_prompt`](AgentBuilder::system_prompt)
    /// - [`template_variables`](AgentBuilder::template_variables)
    /// - [`tools`](AgentBuilder::tools)
    /// - [`built_in_tool_configs`](AgentBuilder::built_in_tool_configs)
    /// - [`tasks`](AgentBuilder::tasks)
    /// - [`generate_no_input_poke_text`](AgentBuilder::generate_no_input_poke_text)
    /// - [`no_input_poke_text`](AgentBuilder::no_input_poke_text)
    /// - [`no_input_end_conversation_sec`](AgentBuilder::no_input_end_conversation_sec)
    /// - [`default_language`](AgentBuilder::default_language)
    /// - [`additional_languages`](AgentBuilder::additional_languages)
    /// - [`multilingual_mode`](AgentBuilder::multilingual_mode)
    /// - [`push_to_talk`](AgentBuilder::push_to_talk)
    /// - [`intelligence_level`](AgentBuilder::intelligence_level)
    /// - [`boosted_keywords`](AgentBuilder::boosted_keywords)
    /// - [`pronunciation_dictionary`](AgentBuilder::pronunciation_dictionary)
    /// - [`min_words_to_interrupt`](AgentBuilder::min_words_to_interrupt)
    pub fn build(self) -> Result<Agent, BuildError> {
        Ok(Agent {
            id: self.id.ok_or_else(|| BuildError::missing_field("id"))?,
            name: self.name.ok_or_else(|| BuildError::missing_field("name"))?,
            phone_number: self.phone_number,
            phone_numbers: self.phone_numbers.ok_or_else(|| BuildError::missing_field("phone_numbers"))?,
            project: self.project.ok_or_else(|| BuildError::missing_field("project"))?,
            timezone: self.timezone.ok_or_else(|| BuildError::missing_field("timezone"))?,
            voice_id: self.voice_id.ok_or_else(|| BuildError::missing_field("voice_id"))?,
            audio_format: self.audio_format.ok_or_else(|| BuildError::missing_field("audio_format"))?,
            audio_speed: self.audio_speed.ok_or_else(|| BuildError::missing_field("audio_speed"))?,
            background_noise_level: self.background_noise_level.ok_or_else(|| BuildError::missing_field("background_noise_level"))?,
            background_noise: self.background_noise,
            generate_welcome_message: self.generate_welcome_message.ok_or_else(|| BuildError::missing_field("generate_welcome_message"))?,
            is_welcome_message_interruptible: self.is_welcome_message_interruptible.ok_or_else(|| BuildError::missing_field("is_welcome_message_interruptible"))?,
            websocket_timeout_sec: self.websocket_timeout_sec,
            welcome_message: self.welcome_message,
            system_prompt: self.system_prompt.ok_or_else(|| BuildError::missing_field("system_prompt"))?,
            template_variables: self.template_variables.ok_or_else(|| BuildError::missing_field("template_variables"))?,
            tools: self.tools.ok_or_else(|| BuildError::missing_field("tools"))?,
            built_in_tool_configs: self.built_in_tool_configs.ok_or_else(|| BuildError::missing_field("built_in_tool_configs"))?,
            tasks: self.tasks.ok_or_else(|| BuildError::missing_field("tasks"))?,
            generate_no_input_poke_text: self.generate_no_input_poke_text.ok_or_else(|| BuildError::missing_field("generate_no_input_poke_text"))?,
            no_input_poke_sec: self.no_input_poke_sec,
            no_input_poke_text: self.no_input_poke_text.ok_or_else(|| BuildError::missing_field("no_input_poke_text"))?,
            no_input_end_conversation_sec: self.no_input_end_conversation_sec.ok_or_else(|| BuildError::missing_field("no_input_end_conversation_sec"))?,
            default_language: self.default_language.ok_or_else(|| BuildError::missing_field("default_language"))?,
            additional_languages: self.additional_languages.ok_or_else(|| BuildError::missing_field("additional_languages"))?,
            languages: self.languages,
            multilingual_mode: self.multilingual_mode.ok_or_else(|| BuildError::missing_field("multilingual_mode"))?,
            push_to_talk: self.push_to_talk.ok_or_else(|| BuildError::missing_field("push_to_talk"))?,
            intelligence_level: self.intelligence_level.ok_or_else(|| BuildError::missing_field("intelligence_level"))?,
            boosted_keywords: self.boosted_keywords.ok_or_else(|| BuildError::missing_field("boosted_keywords"))?,
            observability_integrations: self.observability_integrations,
            pronunciation_dictionary: self.pronunciation_dictionary.ok_or_else(|| BuildError::missing_field("pronunciation_dictionary"))?,
            min_words_to_interrupt: self.min_words_to_interrupt.ok_or_else(|| BuildError::missing_field("min_words_to_interrupt"))?,
            configuration_endpoint: self.configuration_endpoint,
            inbound_rollout: self.inbound_rollout,
            inbound_rollout_forward_phone_number: self.inbound_rollout_forward_phone_number,
            vad_prebuffer_duration_ms: self.vad_prebuffer_duration_ms,
            vad_min_speech_duration_ms: self.vad_min_speech_duration_ms,
            vad_min_silence_duration_ms: self.vad_min_silence_duration_ms,
            vad_threshold: self.vad_threshold,
            enable_redaction: self.enable_redaction,
            slug: self.slug,
            enable_assistant_backchannel: self.enable_assistant_backchannel,
            assistant_backchannel_aggressiveness: self.assistant_backchannel_aggressiveness,
            integrations: self.integrations,
            data_retention_policy: self.data_retention_policy,
        })
    }
}
