pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

/// Configuration fields for the initial `config` message.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct ConfigOptions {
    /// Agent name to use for conversation
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// Project name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// STS model to use
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// System prompt for AI assistant
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    /// Audio playback speed
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub audio_speed: Option<f64>,
    /// Background noise level for the conversation
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub background_noise_level: Option<f64>,
    /// Background noise type for the conversation
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background_noise: Option<ConfigOptionsBackgroundNoise>,
    /// When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_welcome_message: Option<bool>,
    /// When `false`, the welcome message will not be interruptible by the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_welcome_message_interruptible: Option<bool>,
    /// Number of seconds of inactivity before the conversation WebSocket is closed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub websocket_timeout_sec: Option<i64>,
    /// Message to play when conversation starts. Ignored when `generate_welcome_message` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<String>,
    /// Voice ID to use for speech synthesis
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// Audio input format
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_format: Option<ConfigOptionsInputFormat>,
    /// Audio output format
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_format: Option<ConfigOptionsOutputFormat>,
    /// Voice activity detection prebuffer duration
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_prebuffer_duration_ms: Option<i64>,
    /// Minimum speech duration for VAD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_speech_duration_ms: Option<i64>,
    /// Minimum silence duration for VAD
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_silence_duration_ms: Option<i64>,
    /// Voice activity detection threshold
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub vad_threshold: Option<f64>,
    /// Minimum number of words required to interrupt the assistant.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_words_to_interrupt: Option<i64>,
    /// Whether to have the no-input poke text be generated by AI
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_no_input_poke_text: Option<bool>,
    /// Seconds of silence before poke message
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_sec: Option<i64>,
    /// Poke message text. Ignored when generate_no_input_poke_text is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_text: Option<String>,
    /// Seconds of silence before ending conversation
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_end_conversation_sec: Option<i64>,
    /// ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_language: Option<String>,
    /// Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_languages: Option<Vec<String>>,
    /// If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multilingual_mode: Option<ConfigOptionsMultilingualMode>,
    /// Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub push_to_talk: Option<bool>,
    /// When `true`, assistant audio is streamed to the client as fast as it is generated, rather than paced to real time. Defaults to false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream_ahead_of_real_time: Option<bool>,
    /// The intelligence level of the agent. `high` uses a more capable model for more complex reasoning, while `standard` is optimized for lower latency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intelligence_level: Option<ConfigOptionsIntelligenceLevel>,
    /// Keywords to boost in speech recognition
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boosted_keywords: Option<Vec<String>>,
    /// Array of `{ word, pronunciation }` entries. Words must be unique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pronunciation_dictionary: Option<Vec<ConfigOptionsPronunciationDictionaryItem>>,
    /// Tools available to the assistant. Use a string to reference a pre-defined tool by name, or define an inline WebSocket tool for this conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<ToolDefinition>>,
    /// Template variables for system prompt and welcome message
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<HashMap<String, String>>,
    /// When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_redaction: Option<bool>,
    /// Names of pre-configured MCP servers to make available to the assistant. Names must be unique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcp_servers: Option<Vec<String>>,
    /// Names of observability integrations to enable for the conversation. Each must be one of the supported providers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observability_integrations: Option<Vec<String>>,
    /// Tasks the assistant should accomplish during the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<ConfigOptionsTasksItem>>,
    /// Pool of phone numbers to use as the caller ID for outbound calls.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outbound_number_pool: Option<ConfigOptionsOutboundNumberPool>,
    /// When `true`, the assistant will produce backchannel responses (e.g. "mm-hmm", "yeah") while the user is speaking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_assistant_backchannel: Option<bool>,
    /// How aggressively the assistant produces backchannel responses. Only applies when `enable_assistant_backchannel` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub assistant_backchannel_aggressiveness: Option<f64>,
    /// When not `null`, the agent will call this endpoint to get configuration options for the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub configuration_endpoint: Option<ConfigOptionsConfigurationEndpoint>,
    /// Additional runtime parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_params: Option<HashMap<String, serde_json::Value>>,
    /// Policy controlling how long transcripts and audio recordings are retained before being deleted.
    /// When `zero_data_retention` is `true`, nothing is retained and `transcripts`/`audio_recordings` are omitted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_retention_policy: Option<ConfigOptionsDataRetentionPolicy>,
}

impl ConfigOptions {
    pub fn builder() -> ConfigOptionsBuilder {
        <ConfigOptionsBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct ConfigOptionsBuilder {
    agent: Option<String>,
    project: Option<String>,
    model: Option<String>,
    system_prompt: Option<String>,
    audio_speed: Option<f64>,
    background_noise_level: Option<f64>,
    background_noise: Option<ConfigOptionsBackgroundNoise>,
    generate_welcome_message: Option<bool>,
    is_welcome_message_interruptible: Option<bool>,
    websocket_timeout_sec: Option<i64>,
    welcome_message: Option<String>,
    voice_id: Option<String>,
    input_format: Option<ConfigOptionsInputFormat>,
    output_format: Option<ConfigOptionsOutputFormat>,
    vad_prebuffer_duration_ms: Option<i64>,
    vad_min_speech_duration_ms: Option<i64>,
    vad_min_silence_duration_ms: Option<i64>,
    vad_threshold: Option<f64>,
    min_words_to_interrupt: Option<i64>,
    generate_no_input_poke_text: Option<bool>,
    no_input_poke_sec: Option<i64>,
    no_input_poke_text: Option<String>,
    no_input_end_conversation_sec: Option<i64>,
    default_language: Option<String>,
    additional_languages: Option<Vec<String>>,
    multilingual_mode: Option<ConfigOptionsMultilingualMode>,
    push_to_talk: Option<bool>,
    stream_ahead_of_real_time: Option<bool>,
    intelligence_level: Option<ConfigOptionsIntelligenceLevel>,
    boosted_keywords: Option<Vec<String>>,
    pronunciation_dictionary: Option<Vec<ConfigOptionsPronunciationDictionaryItem>>,
    tools: Option<Vec<ToolDefinition>>,
    template_variables: Option<HashMap<String, String>>,
    enable_redaction: Option<bool>,
    mcp_servers: Option<Vec<String>>,
    observability_integrations: Option<Vec<String>>,
    tasks: Option<Vec<ConfigOptionsTasksItem>>,
    outbound_number_pool: Option<ConfigOptionsOutboundNumberPool>,
    enable_assistant_backchannel: Option<bool>,
    assistant_backchannel_aggressiveness: Option<f64>,
    configuration_endpoint: Option<ConfigOptionsConfigurationEndpoint>,
    additional_params: Option<HashMap<String, serde_json::Value>>,
    data_retention_policy: Option<ConfigOptionsDataRetentionPolicy>,
}

impl ConfigOptionsBuilder {
    pub fn agent(mut self, value: impl Into<String>) -> Self {
        self.agent = Some(value.into());
        self
    }

    pub fn project(mut self, value: impl Into<String>) -> Self {
        self.project = Some(value.into());
        self
    }

    pub fn model(mut self, value: impl Into<String>) -> Self {
        self.model = Some(value.into());
        self
    }

    pub fn system_prompt(mut self, value: impl Into<String>) -> Self {
        self.system_prompt = Some(value.into());
        self
    }

    pub fn audio_speed(mut self, value: f64) -> Self {
        self.audio_speed = Some(value);
        self
    }

    pub fn background_noise_level(mut self, value: f64) -> Self {
        self.background_noise_level = Some(value);
        self
    }

    pub fn background_noise(mut self, value: ConfigOptionsBackgroundNoise) -> Self {
        self.background_noise = Some(value);
        self
    }

    pub fn generate_welcome_message(mut self, value: bool) -> Self {
        self.generate_welcome_message = Some(value);
        self
    }

    pub fn is_welcome_message_interruptible(mut self, value: bool) -> Self {
        self.is_welcome_message_interruptible = Some(value);
        self
    }

    pub fn websocket_timeout_sec(mut self, value: i64) -> Self {
        self.websocket_timeout_sec = Some(value);
        self
    }

    pub fn welcome_message(mut self, value: impl Into<String>) -> Self {
        self.welcome_message = Some(value.into());
        self
    }

    pub fn voice_id(mut self, value: impl Into<String>) -> Self {
        self.voice_id = Some(value.into());
        self
    }

    pub fn input_format(mut self, value: ConfigOptionsInputFormat) -> Self {
        self.input_format = Some(value);
        self
    }

    pub fn output_format(mut self, value: ConfigOptionsOutputFormat) -> Self {
        self.output_format = Some(value);
        self
    }

    pub fn vad_prebuffer_duration_ms(mut self, value: i64) -> Self {
        self.vad_prebuffer_duration_ms = Some(value);
        self
    }

    pub fn vad_min_speech_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_speech_duration_ms = Some(value);
        self
    }

    pub fn vad_min_silence_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_silence_duration_ms = Some(value);
        self
    }

    pub fn vad_threshold(mut self, value: f64) -> Self {
        self.vad_threshold = Some(value);
        self
    }

    pub fn min_words_to_interrupt(mut self, value: i64) -> Self {
        self.min_words_to_interrupt = Some(value);
        self
    }

    pub fn generate_no_input_poke_text(mut self, value: bool) -> Self {
        self.generate_no_input_poke_text = Some(value);
        self
    }

    pub fn no_input_poke_sec(mut self, value: i64) -> Self {
        self.no_input_poke_sec = Some(value);
        self
    }

    pub fn no_input_poke_text(mut self, value: impl Into<String>) -> Self {
        self.no_input_poke_text = Some(value.into());
        self
    }

    pub fn no_input_end_conversation_sec(mut self, value: i64) -> Self {
        self.no_input_end_conversation_sec = Some(value);
        self
    }

    pub fn default_language(mut self, value: impl Into<String>) -> Self {
        self.default_language = Some(value.into());
        self
    }

    pub fn additional_languages(mut self, value: Vec<String>) -> Self {
        self.additional_languages = Some(value);
        self
    }

    pub fn multilingual_mode(mut self, value: ConfigOptionsMultilingualMode) -> Self {
        self.multilingual_mode = Some(value);
        self
    }

    pub fn push_to_talk(mut self, value: bool) -> Self {
        self.push_to_talk = Some(value);
        self
    }

    pub fn stream_ahead_of_real_time(mut self, value: bool) -> Self {
        self.stream_ahead_of_real_time = Some(value);
        self
    }

    pub fn intelligence_level(mut self, value: ConfigOptionsIntelligenceLevel) -> Self {
        self.intelligence_level = Some(value);
        self
    }

    pub fn boosted_keywords(mut self, value: Vec<String>) -> Self {
        self.boosted_keywords = Some(value);
        self
    }

    pub fn pronunciation_dictionary(mut self, value: Vec<ConfigOptionsPronunciationDictionaryItem>) -> Self {
        self.pronunciation_dictionary = Some(value);
        self
    }

    pub fn tools(mut self, value: Vec<ToolDefinition>) -> Self {
        self.tools = Some(value);
        self
    }

    pub fn template_variables(mut self, value: HashMap<String, String>) -> Self {
        self.template_variables = Some(value);
        self
    }

    pub fn enable_redaction(mut self, value: bool) -> Self {
        self.enable_redaction = Some(value);
        self
    }

    pub fn mcp_servers(mut self, value: Vec<String>) -> Self {
        self.mcp_servers = Some(value);
        self
    }

    pub fn observability_integrations(mut self, value: Vec<String>) -> Self {
        self.observability_integrations = Some(value);
        self
    }

    pub fn tasks(mut self, value: Vec<ConfigOptionsTasksItem>) -> Self {
        self.tasks = Some(value);
        self
    }

    pub fn outbound_number_pool(mut self, value: ConfigOptionsOutboundNumberPool) -> Self {
        self.outbound_number_pool = Some(value);
        self
    }

    pub fn enable_assistant_backchannel(mut self, value: bool) -> Self {
        self.enable_assistant_backchannel = Some(value);
        self
    }

    pub fn assistant_backchannel_aggressiveness(mut self, value: f64) -> Self {
        self.assistant_backchannel_aggressiveness = Some(value);
        self
    }

    pub fn configuration_endpoint(mut self, value: ConfigOptionsConfigurationEndpoint) -> Self {
        self.configuration_endpoint = Some(value);
        self
    }

    pub fn additional_params(mut self, value: HashMap<String, serde_json::Value>) -> Self {
        self.additional_params = Some(value);
        self
    }

    pub fn data_retention_policy(mut self, value: ConfigOptionsDataRetentionPolicy) -> Self {
        self.data_retention_policy = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`ConfigOptions`].
    pub fn build(self) -> Result<ConfigOptions, BuildError> {
        Ok(ConfigOptions {
            agent: self.agent,
            project: self.project,
            model: self.model,
            system_prompt: self.system_prompt,
            audio_speed: self.audio_speed,
            background_noise_level: self.background_noise_level,
            background_noise: self.background_noise,
            generate_welcome_message: self.generate_welcome_message,
            is_welcome_message_interruptible: self.is_welcome_message_interruptible,
            websocket_timeout_sec: self.websocket_timeout_sec,
            welcome_message: self.welcome_message,
            voice_id: self.voice_id,
            input_format: self.input_format,
            output_format: self.output_format,
            vad_prebuffer_duration_ms: self.vad_prebuffer_duration_ms,
            vad_min_speech_duration_ms: self.vad_min_speech_duration_ms,
            vad_min_silence_duration_ms: self.vad_min_silence_duration_ms,
            vad_threshold: self.vad_threshold,
            min_words_to_interrupt: self.min_words_to_interrupt,
            generate_no_input_poke_text: self.generate_no_input_poke_text,
            no_input_poke_sec: self.no_input_poke_sec,
            no_input_poke_text: self.no_input_poke_text,
            no_input_end_conversation_sec: self.no_input_end_conversation_sec,
            default_language: self.default_language,
            additional_languages: self.additional_languages,
            multilingual_mode: self.multilingual_mode,
            push_to_talk: self.push_to_talk,
            stream_ahead_of_real_time: self.stream_ahead_of_real_time,
            intelligence_level: self.intelligence_level,
            boosted_keywords: self.boosted_keywords,
            pronunciation_dictionary: self.pronunciation_dictionary,
            tools: self.tools,
            template_variables: self.template_variables,
            enable_redaction: self.enable_redaction,
            mcp_servers: self.mcp_servers,
            observability_integrations: self.observability_integrations,
            tasks: self.tasks,
            outbound_number_pool: self.outbound_number_pool,
            enable_assistant_backchannel: self.enable_assistant_backchannel,
            assistant_backchannel_aggressiveness: self.assistant_backchannel_aggressiveness,
            configuration_endpoint: self.configuration_endpoint,
            additional_params: self.additional_params,
            data_retention_policy: self.data_retention_policy,
        })
    }
}
