pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct CreateAgentRequest {
    /// The name of the agent. Can only contain lowercase letters, numbers and hyphens. Must be unique within the project.
    #[serde(default)]
    pub name: String,
    /// URL-friendly agent slug. Can only contain lowercase letters, numbers and hyphens. Must be unique within the project.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    /// When set to `null`, the agent will not be associated with a phone number. When set to `"assign-automatically"`, the agent will be assigned a random phone number. When set to `"custom"`, you must provide `custom_phone_numbers`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<CreateAgentRequestPhoneNumber>,
    /// The custom phone number to use for the agent in E.164 format (e.g., +1234567890). This field is deprecated. Use `custom_phone_numbers` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_phone_number: Option<String>,
    /// Array of custom phone numbers in E.164 format (e.g., ["+1234567890", "+0987654321"]). The agent will be able to receive phone calls on any of these numbers. Required when `phone_number` is set to `"custom"`. All phone numbers must be unique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_phone_numbers: Option<Vec<String>>,
    /// The timezone of the agent. Used to format system variables like `{{system_time}}`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// The voice ID to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// The audio format of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio_format: Option<CreateAgentRequestAudioFormat>,
    /// The audio speed of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub audio_speed: Option<f64>,
    /// The background noise level of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub background_noise_level: Option<f64>,
    /// The background noise type. Can be "office", "call-center", "coffee-shop", or null.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background_noise: Option<CreateAgentRequestBackgroundNoise>,
    /// When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_welcome_message: Option<bool>,
    /// When `false`, the welcome message will not be interruptible by the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_welcome_message_interruptible: Option<bool>,
    /// Number of seconds of inactivity before the conversation WebSocket is closed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub websocket_timeout_sec: Option<i64>,
    /// Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`. Ignored when `generate_welcome_message` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<String>,
    /// Instructions for the conversation. Can contain template variables like `{{subject}}`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    /// Variables that can be used in the welcome message and the system prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<HashMap<String, CreateAgentRequestTemplateVariablesValue>>,
    /// Array of built-in or custom tool names to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<CreateAgentRequestToolsItem>>,
    /// Array of task objects with `name` and `description` fields.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<Task>>,
    /// Whether to have the no-input poke text be generated by AI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_no_input_poke_text: Option<bool>,
    /// Number of seconds of silence before sending a poke message. `null` disables the poke message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_sec: Option<i64>,
    /// The message to send after the specified silence. Ignored when generate_no_input_poke_text is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_text: Option<String>,
    /// Seconds of silence before ending the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_end_conversation_sec: Option<i64>,
    /// When `true`, the assistant will produce backchannel responses (e.g. "mm-hmm") while the user is speaking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_assistant_backchannel: Option<bool>,
    /// How aggressively the assistant produces backchannel responses. Only relevant when `enable_assistant_backchannel` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub assistant_backchannel_aggressiveness: Option<f64>,
    /// Controls how long transcripts and audio recordings are retained before deletion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_retention_policy: Option<DataRetentionPolicy>,
    /// ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_language: Option<LanguageCode>,
    /// Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_languages: Option<Vec<LanguageCode>>,
    /// Array of ISO 639-1 language codes that the agent should be able to recognize. This field is deprecated. Use `default_language` and `additional_languages` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<LanguageCode>>,
    /// If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multilingual_mode: Option<CreateAgentRequestMultilingualMode>,
    /// Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub push_to_talk: Option<bool>,
    /// The intelligence level of the agent. `high` uses a more capable model for more complex reasoning, while `standard` is optimized for lower latency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intelligence_level: Option<CreateAgentRequestIntelligenceLevel>,
    /// These words, or short phrases, will be more accurately recognized by the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boosted_keywords: Option<Vec<String>>,
    /// Array of `{ word, pronunciation }` entries. Words must be unique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pronunciation_dictionary: Option<Vec<CreateAgentRequestPronunciationDictionaryItem>>,
    /// Minimum number of words required to interrupt the assistant.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_words_to_interrupt: Option<i64>,
    /// When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint to get configuration options.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub configuration_endpoint: Option<CreateAgentRequestConfigurationEndpoint>,
    /// Float between 0.0 and 1.0 representing the percentage of inbound calls handled by Agent. Defaults to `1.0`. Requires `phone_number` to be set when less than 1.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub inbound_rollout: Option<f64>,
    /// E.164 formatted phone number where non-agent calls will be forwarded. Required when `inbound_rollout < 1.0`, must be `null` when `inbound_rollout = 1.0`. Defaults to `null`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub inbound_rollout_forward_phone_number: Option<String>,
    /// Voice activity detection prebuffer duration in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_prebuffer_duration_ms: Option<i64>,
    /// Minimum speech duration for voice activity detection in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_speech_duration_ms: Option<i64>,
    /// Minimum silence duration for voice activity detection in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vad_min_silence_duration_ms: Option<i64>,
    /// Voice activity detection threshold.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub vad_threshold: Option<f64>,
    /// When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_redaction: Option<bool>,
    /// Array of MCP server IDs to make available to the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcp_server_ids: Option<Vec<String>>,
    /// Names of observability integrations to enable for the agent. Each must be one of the supported providers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub observability_integrations: Option<Vec<String>>,
}

impl CreateAgentRequest {
    pub fn builder() -> CreateAgentRequestBuilder {
        <CreateAgentRequestBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct CreateAgentRequestBuilder {
    name: Option<String>,
    slug: Option<String>,
    phone_number: Option<CreateAgentRequestPhoneNumber>,
    custom_phone_number: Option<String>,
    custom_phone_numbers: Option<Vec<String>>,
    timezone: Option<String>,
    voice_id: Option<String>,
    audio_format: Option<CreateAgentRequestAudioFormat>,
    audio_speed: Option<f64>,
    background_noise_level: Option<f64>,
    background_noise: Option<CreateAgentRequestBackgroundNoise>,
    generate_welcome_message: Option<bool>,
    is_welcome_message_interruptible: Option<bool>,
    websocket_timeout_sec: Option<i64>,
    welcome_message: Option<String>,
    system_prompt: Option<String>,
    template_variables: Option<HashMap<String, CreateAgentRequestTemplateVariablesValue>>,
    tools: Option<Vec<CreateAgentRequestToolsItem>>,
    tasks: Option<Vec<Task>>,
    generate_no_input_poke_text: Option<bool>,
    no_input_poke_sec: Option<i64>,
    no_input_poke_text: Option<String>,
    no_input_end_conversation_sec: Option<i64>,
    enable_assistant_backchannel: Option<bool>,
    assistant_backchannel_aggressiveness: Option<f64>,
    data_retention_policy: Option<DataRetentionPolicy>,
    default_language: Option<LanguageCode>,
    additional_languages: Option<Vec<LanguageCode>>,
    languages: Option<Vec<LanguageCode>>,
    multilingual_mode: Option<CreateAgentRequestMultilingualMode>,
    push_to_talk: Option<bool>,
    intelligence_level: Option<CreateAgentRequestIntelligenceLevel>,
    boosted_keywords: Option<Vec<String>>,
    pronunciation_dictionary: Option<Vec<CreateAgentRequestPronunciationDictionaryItem>>,
    min_words_to_interrupt: Option<i64>,
    configuration_endpoint: Option<CreateAgentRequestConfigurationEndpoint>,
    inbound_rollout: Option<f64>,
    inbound_rollout_forward_phone_number: Option<String>,
    vad_prebuffer_duration_ms: Option<i64>,
    vad_min_speech_duration_ms: Option<i64>,
    vad_min_silence_duration_ms: Option<i64>,
    vad_threshold: Option<f64>,
    enable_redaction: Option<bool>,
    mcp_server_ids: Option<Vec<String>>,
    observability_integrations: Option<Vec<String>>,
}

impl CreateAgentRequestBuilder {
    pub fn name(mut self, value: impl Into<String>) -> Self {
        self.name = Some(value.into());
        self
    }

    pub fn slug(mut self, value: impl Into<String>) -> Self {
        self.slug = Some(value.into());
        self
    }

    pub fn phone_number(mut self, value: CreateAgentRequestPhoneNumber) -> Self {
        self.phone_number = Some(value);
        self
    }

    pub fn custom_phone_number(mut self, value: impl Into<String>) -> Self {
        self.custom_phone_number = Some(value.into());
        self
    }

    pub fn custom_phone_numbers(mut self, value: Vec<String>) -> Self {
        self.custom_phone_numbers = Some(value);
        self
    }

    pub fn timezone(mut self, value: impl Into<String>) -> Self {
        self.timezone = Some(value.into());
        self
    }

    pub fn voice_id(mut self, value: impl Into<String>) -> Self {
        self.voice_id = Some(value.into());
        self
    }

    pub fn audio_format(mut self, value: CreateAgentRequestAudioFormat) -> Self {
        self.audio_format = Some(value);
        self
    }

    pub fn audio_speed(mut self, value: f64) -> Self {
        self.audio_speed = Some(value);
        self
    }

    pub fn background_noise_level(mut self, value: f64) -> Self {
        self.background_noise_level = Some(value);
        self
    }

    pub fn background_noise(mut self, value: CreateAgentRequestBackgroundNoise) -> Self {
        self.background_noise = Some(value);
        self
    }

    pub fn generate_welcome_message(mut self, value: bool) -> Self {
        self.generate_welcome_message = Some(value);
        self
    }

    pub fn is_welcome_message_interruptible(mut self, value: bool) -> Self {
        self.is_welcome_message_interruptible = Some(value);
        self
    }

    pub fn websocket_timeout_sec(mut self, value: i64) -> Self {
        self.websocket_timeout_sec = Some(value);
        self
    }

    pub fn welcome_message(mut self, value: impl Into<String>) -> Self {
        self.welcome_message = Some(value.into());
        self
    }

    pub fn system_prompt(mut self, value: impl Into<String>) -> Self {
        self.system_prompt = Some(value.into());
        self
    }

    pub fn template_variables(mut self, value: HashMap<String, CreateAgentRequestTemplateVariablesValue>) -> Self {
        self.template_variables = Some(value);
        self
    }

    pub fn tools(mut self, value: Vec<CreateAgentRequestToolsItem>) -> Self {
        self.tools = Some(value);
        self
    }

    pub fn tasks(mut self, value: Vec<Task>) -> Self {
        self.tasks = Some(value);
        self
    }

    pub fn generate_no_input_poke_text(mut self, value: bool) -> Self {
        self.generate_no_input_poke_text = Some(value);
        self
    }

    pub fn no_input_poke_sec(mut self, value: i64) -> Self {
        self.no_input_poke_sec = Some(value);
        self
    }

    pub fn no_input_poke_text(mut self, value: impl Into<String>) -> Self {
        self.no_input_poke_text = Some(value.into());
        self
    }

    pub fn no_input_end_conversation_sec(mut self, value: i64) -> Self {
        self.no_input_end_conversation_sec = Some(value);
        self
    }

    pub fn enable_assistant_backchannel(mut self, value: bool) -> Self {
        self.enable_assistant_backchannel = Some(value);
        self
    }

    pub fn assistant_backchannel_aggressiveness(mut self, value: f64) -> Self {
        self.assistant_backchannel_aggressiveness = Some(value);
        self
    }

    pub fn data_retention_policy(mut self, value: DataRetentionPolicy) -> Self {
        self.data_retention_policy = Some(value);
        self
    }

    pub fn default_language(mut self, value: LanguageCode) -> Self {
        self.default_language = Some(value);
        self
    }

    pub fn additional_languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.additional_languages = Some(value);
        self
    }

    pub fn languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.languages = Some(value);
        self
    }

    pub fn multilingual_mode(mut self, value: CreateAgentRequestMultilingualMode) -> Self {
        self.multilingual_mode = Some(value);
        self
    }

    pub fn push_to_talk(mut self, value: bool) -> Self {
        self.push_to_talk = Some(value);
        self
    }

    pub fn intelligence_level(mut self, value: CreateAgentRequestIntelligenceLevel) -> Self {
        self.intelligence_level = Some(value);
        self
    }

    pub fn boosted_keywords(mut self, value: Vec<String>) -> Self {
        self.boosted_keywords = Some(value);
        self
    }

    pub fn pronunciation_dictionary(mut self, value: Vec<CreateAgentRequestPronunciationDictionaryItem>) -> Self {
        self.pronunciation_dictionary = Some(value);
        self
    }

    pub fn min_words_to_interrupt(mut self, value: i64) -> Self {
        self.min_words_to_interrupt = Some(value);
        self
    }

    pub fn configuration_endpoint(mut self, value: CreateAgentRequestConfigurationEndpoint) -> Self {
        self.configuration_endpoint = Some(value);
        self
    }

    pub fn inbound_rollout(mut self, value: f64) -> Self {
        self.inbound_rollout = Some(value);
        self
    }

    pub fn inbound_rollout_forward_phone_number(mut self, value: impl Into<String>) -> Self {
        self.inbound_rollout_forward_phone_number = Some(value.into());
        self
    }

    pub fn vad_prebuffer_duration_ms(mut self, value: i64) -> Self {
        self.vad_prebuffer_duration_ms = Some(value);
        self
    }

    pub fn vad_min_speech_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_speech_duration_ms = Some(value);
        self
    }

    pub fn vad_min_silence_duration_ms(mut self, value: i64) -> Self {
        self.vad_min_silence_duration_ms = Some(value);
        self
    }

    pub fn vad_threshold(mut self, value: f64) -> Self {
        self.vad_threshold = Some(value);
        self
    }

    pub fn enable_redaction(mut self, value: bool) -> Self {
        self.enable_redaction = Some(value);
        self
    }

    pub fn mcp_server_ids(mut self, value: Vec<String>) -> Self {
        self.mcp_server_ids = Some(value);
        self
    }

    pub fn observability_integrations(mut self, value: Vec<String>) -> Self {
        self.observability_integrations = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`CreateAgentRequest`].
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](CreateAgentRequestBuilder::name)
    pub fn build(self) -> Result<CreateAgentRequest, BuildError> {
        Ok(CreateAgentRequest {
            name: self.name.ok_or_else(|| BuildError::missing_field("name"))?,
            slug: self.slug,
            phone_number: self.phone_number,
            custom_phone_number: self.custom_phone_number,
            custom_phone_numbers: self.custom_phone_numbers,
            timezone: self.timezone,
            voice_id: self.voice_id,
            audio_format: self.audio_format,
            audio_speed: self.audio_speed,
            background_noise_level: self.background_noise_level,
            background_noise: self.background_noise,
            generate_welcome_message: self.generate_welcome_message,
            is_welcome_message_interruptible: self.is_welcome_message_interruptible,
            websocket_timeout_sec: self.websocket_timeout_sec,
            welcome_message: self.welcome_message,
            system_prompt: self.system_prompt,
            template_variables: self.template_variables,
            tools: self.tools,
            tasks: self.tasks,
            generate_no_input_poke_text: self.generate_no_input_poke_text,
            no_input_poke_sec: self.no_input_poke_sec,
            no_input_poke_text: self.no_input_poke_text,
            no_input_end_conversation_sec: self.no_input_end_conversation_sec,
            enable_assistant_backchannel: self.enable_assistant_backchannel,
            assistant_backchannel_aggressiveness: self.assistant_backchannel_aggressiveness,
            data_retention_policy: self.data_retention_policy,
            default_language: self.default_language,
            additional_languages: self.additional_languages,
            languages: self.languages,
            multilingual_mode: self.multilingual_mode,
            push_to_talk: self.push_to_talk,
            intelligence_level: self.intelligence_level,
            boosted_keywords: self.boosted_keywords,
            pronunciation_dictionary: self.pronunciation_dictionary,
            min_words_to_interrupt: self.min_words_to_interrupt,
            configuration_endpoint: self.configuration_endpoint,
            inbound_rollout: self.inbound_rollout,
            inbound_rollout_forward_phone_number: self.inbound_rollout_forward_phone_number,
            vad_prebuffer_duration_ms: self.vad_prebuffer_duration_ms,
            vad_min_speech_duration_ms: self.vad_min_speech_duration_ms,
            vad_min_silence_duration_ms: self.vad_min_silence_duration_ms,
            vad_threshold: self.vad_threshold,
            enable_redaction: self.enable_redaction,
            mcp_server_ids: self.mcp_server_ids,
            observability_integrations: self.observability_integrations,
        })
    }
}
