pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

/// ISO 639-1 language codes supported by the agent
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum LanguageCode {
    Ar,
    Az,
    Bg,
    Bn,
    Cs,
    Da,
    De,
    El,
    En,
    Es,
    Fa,
    Fi,
    Fil,
    Fr,
    Gu,
    He,
    Hi,
    Hu,
    Id,
    It,
    Ja,
    Ka,
    Km,
    Kn,
    Ko,
    Lt,
    Lv,
    Ml,
    Mr,
    Ms,
    Ne,
    Nl,
    No,
    Pa,
    Pl,
    Pt,
    Ro,
    Ru,
    Si,
    Sk,
    Sq,
    Sv,
    Sw,
    Ta,
    Te,
    Th,
    Tr,
    Uk,
    Ur,
    Vi,
    Yue,
    Zh,
    /// This variant is used for forward compatibility.
    /// If the server sends a value not recognized by the current SDK version,
    /// it will be captured here with the raw string value.
    __Unknown(String),
}
impl Serialize for LanguageCode {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Ar => serializer.serialize_str("ar"),
            Self::Az => serializer.serialize_str("az"),
            Self::Bg => serializer.serialize_str("bg"),
            Self::Bn => serializer.serialize_str("bn"),
            Self::Cs => serializer.serialize_str("cs"),
            Self::Da => serializer.serialize_str("da"),
            Self::De => serializer.serialize_str("de"),
            Self::El => serializer.serialize_str("el"),
            Self::En => serializer.serialize_str("en"),
            Self::Es => serializer.serialize_str("es"),
            Self::Fa => serializer.serialize_str("fa"),
            Self::Fi => serializer.serialize_str("fi"),
            Self::Fil => serializer.serialize_str("fil"),
            Self::Fr => serializer.serialize_str("fr"),
            Self::Gu => serializer.serialize_str("gu"),
            Self::He => serializer.serialize_str("he"),
            Self::Hi => serializer.serialize_str("hi"),
            Self::Hu => serializer.serialize_str("hu"),
            Self::Id => serializer.serialize_str("id"),
            Self::It => serializer.serialize_str("it"),
            Self::Ja => serializer.serialize_str("ja"),
            Self::Ka => serializer.serialize_str("ka"),
            Self::Km => serializer.serialize_str("km"),
            Self::Kn => serializer.serialize_str("kn"),
            Self::Ko => serializer.serialize_str("ko"),
            Self::Lt => serializer.serialize_str("lt"),
            Self::Lv => serializer.serialize_str("lv"),
            Self::Ml => serializer.serialize_str("ml"),
            Self::Mr => serializer.serialize_str("mr"),
            Self::Ms => serializer.serialize_str("ms"),
            Self::Ne => serializer.serialize_str("ne"),
            Self::Nl => serializer.serialize_str("nl"),
            Self::No => serializer.serialize_str("no"),
            Self::Pa => serializer.serialize_str("pa"),
            Self::Pl => serializer.serialize_str("pl"),
            Self::Pt => serializer.serialize_str("pt"),
            Self::Ro => serializer.serialize_str("ro"),
            Self::Ru => serializer.serialize_str("ru"),
            Self::Si => serializer.serialize_str("si"),
            Self::Sk => serializer.serialize_str("sk"),
            Self::Sq => serializer.serialize_str("sq"),
            Self::Sv => serializer.serialize_str("sv"),
            Self::Sw => serializer.serialize_str("sw"),
            Self::Ta => serializer.serialize_str("ta"),
            Self::Te => serializer.serialize_str("te"),
            Self::Th => serializer.serialize_str("th"),
            Self::Tr => serializer.serialize_str("tr"),
            Self::Uk => serializer.serialize_str("uk"),
            Self::Ur => serializer.serialize_str("ur"),
            Self::Vi => serializer.serialize_str("vi"),
            Self::Yue => serializer.serialize_str("yue"),
            Self::Zh => serializer.serialize_str("zh"),
            Self::__Unknown(val) => serializer.serialize_str(val),
        }
    }
}

impl<'de> Deserialize<'de> for LanguageCode {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "ar" => Ok(Self::Ar),
            "az" => Ok(Self::Az),
            "bg" => Ok(Self::Bg),
            "bn" => Ok(Self::Bn),
            "cs" => Ok(Self::Cs),
            "da" => Ok(Self::Da),
            "de" => Ok(Self::De),
            "el" => Ok(Self::El),
            "en" => Ok(Self::En),
            "es" => Ok(Self::Es),
            "fa" => Ok(Self::Fa),
            "fi" => Ok(Self::Fi),
            "fil" => Ok(Self::Fil),
            "fr" => Ok(Self::Fr),
            "gu" => Ok(Self::Gu),
            "he" => Ok(Self::He),
            "hi" => Ok(Self::Hi),
            "hu" => Ok(Self::Hu),
            "id" => Ok(Self::Id),
            "it" => Ok(Self::It),
            "ja" => Ok(Self::Ja),
            "ka" => Ok(Self::Ka),
            "km" => Ok(Self::Km),
            "kn" => Ok(Self::Kn),
            "ko" => Ok(Self::Ko),
            "lt" => Ok(Self::Lt),
            "lv" => Ok(Self::Lv),
            "ml" => Ok(Self::Ml),
            "mr" => Ok(Self::Mr),
            "ms" => Ok(Self::Ms),
            "ne" => Ok(Self::Ne),
            "nl" => Ok(Self::Nl),
            "no" => Ok(Self::No),
            "pa" => Ok(Self::Pa),
            "pl" => Ok(Self::Pl),
            "pt" => Ok(Self::Pt),
            "ro" => Ok(Self::Ro),
            "ru" => Ok(Self::Ru),
            "si" => Ok(Self::Si),
            "sk" => Ok(Self::Sk),
            "sq" => Ok(Self::Sq),
            "sv" => Ok(Self::Sv),
            "sw" => Ok(Self::Sw),
            "ta" => Ok(Self::Ta),
            "te" => Ok(Self::Te),
            "th" => Ok(Self::Th),
            "tr" => Ok(Self::Tr),
            "uk" => Ok(Self::Uk),
            "ur" => Ok(Self::Ur),
            "vi" => Ok(Self::Vi),
            "yue" => Ok(Self::Yue),
            "zh" => Ok(Self::Zh),
            _ => Ok(Self::__Unknown(value)),
        }
    }
}

impl fmt::Display for LanguageCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Ar => write!(f, "ar"),
            Self::Az => write!(f, "az"),
            Self::Bg => write!(f, "bg"),
            Self::Bn => write!(f, "bn"),
            Self::Cs => write!(f, "cs"),
            Self::Da => write!(f, "da"),
            Self::De => write!(f, "de"),
            Self::El => write!(f, "el"),
            Self::En => write!(f, "en"),
            Self::Es => write!(f, "es"),
            Self::Fa => write!(f, "fa"),
            Self::Fi => write!(f, "fi"),
            Self::Fil => write!(f, "fil"),
            Self::Fr => write!(f, "fr"),
            Self::Gu => write!(f, "gu"),
            Self::He => write!(f, "he"),
            Self::Hi => write!(f, "hi"),
            Self::Hu => write!(f, "hu"),
            Self::Id => write!(f, "id"),
            Self::It => write!(f, "it"),
            Self::Ja => write!(f, "ja"),
            Self::Ka => write!(f, "ka"),
            Self::Km => write!(f, "km"),
            Self::Kn => write!(f, "kn"),
            Self::Ko => write!(f, "ko"),
            Self::Lt => write!(f, "lt"),
            Self::Lv => write!(f, "lv"),
            Self::Ml => write!(f, "ml"),
            Self::Mr => write!(f, "mr"),
            Self::Ms => write!(f, "ms"),
            Self::Ne => write!(f, "ne"),
            Self::Nl => write!(f, "nl"),
            Self::No => write!(f, "no"),
            Self::Pa => write!(f, "pa"),
            Self::Pl => write!(f, "pl"),
            Self::Pt => write!(f, "pt"),
            Self::Ro => write!(f, "ro"),
            Self::Ru => write!(f, "ru"),
            Self::Si => write!(f, "si"),
            Self::Sk => write!(f, "sk"),
            Self::Sq => write!(f, "sq"),
            Self::Sv => write!(f, "sv"),
            Self::Sw => write!(f, "sw"),
            Self::Ta => write!(f, "ta"),
            Self::Te => write!(f, "te"),
            Self::Th => write!(f, "th"),
            Self::Tr => write!(f, "tr"),
            Self::Uk => write!(f, "uk"),
            Self::Ur => write!(f, "ur"),
            Self::Vi => write!(f, "vi"),
            Self::Yue => write!(f, "yue"),
            Self::Zh => write!(f, "zh"),
            Self::__Unknown(val) => write!(f, "{}", val),
        }
    }
}
