pub use crate::prelude::*;
#[allow(unused_imports)]
use super::*;

/// When an `agent` is provided, these `config` options override the agent settings.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct OutboundCallConfig {
    /// The name of the agent to use for the call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
    /// The name of the project to use for the call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// When `true`, the welcome message will be automatically generated and the `welcome_message` field will be ignored.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_welcome_message: Option<bool>,
    /// When `false`, the welcome message will not be interruptible by the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_welcome_message_interruptible: Option<bool>,
    /// Message to play when the conversation starts. Can contain template variables like `{{customer_name}}`. Ignored when `generate_welcome_message` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<String>,
    /// Instructions for the conversation. Can contain template variables like `{{subject}}`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    /// Variables that can be used in the welcome message and the system prompt.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub template_variables: Option<HashMap<String, String>>,
    /// The voice ID to use for the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub voice_id: Option<String>,
    /// Whether to have the no-input poke text be generated by AI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub generate_no_input_poke_text: Option<bool>,
    /// Number of seconds of silence before sending a poke message. `null` disables the poke message.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_sec: Option<i64>,
    /// The message to send after the specified silence. Ignored when generate_no_input_poke_text is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_poke_text: Option<String>,
    /// Seconds of silence before ending the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub no_input_end_conversation_sec: Option<i64>,
    /// ISO 639-1 language code that sets the agent's default language to recognize and speak. Welcome message and no input poke text should be in this language.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_language: Option<LanguageCode>,
    /// Array of additional ISO 639-1 language codes that the agent should be able to recognize and speak. Should not include `default_language`. When `multilingual_mode` is `"auto"`, a maximum of 2 additional languages is allowed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub additional_languages: Option<Vec<LanguageCode>>,
    /// Array of ISO 639-1 language codes that the agent should be able to recognize. This field is deprecated. Use `default_language` and `additional_languages` instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<LanguageCode>>,
    /// If `"auto"`, each user audio is automatically identified for the language to respond in. If `"request"`, user must request to change language (recommended). If `"initial"` the first turn user audio determines the language for the rest of the conversation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub multilingual_mode: Option<OutboundCallConfigMultilingualMode>,
    /// Push to talk mode. User must send mute/unmute messages to turn on/off listening to audio. Defaults to false.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub push_to_talk: Option<bool>,
    /// The intelligence level of the agent. `high` uses a more capable model for more complex reasoning, while `standard` is optimized for lower latency.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intelligence_level: Option<OutboundCallConfigIntelligenceLevel>,
    /// These words, or short phrases, will be more accurately recognized by the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub boosted_keywords: Option<Vec<String>>,
    /// Array of `{ word, pronunciation }` entries. Words must be unique.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pronunciation_dictionary: Option<Vec<OutboundCallConfigPronunciationDictionaryItem>>,
    /// Minimum number of words required to interrupt the assistant.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_words_to_interrupt: Option<i64>,
    /// Array of built-in or custom tool names to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<OutboundCallConfigToolsItem>>,
    /// When `true`, PII and PHI are redacted from text transcripts (e.g. replaced with tags like `[PHONE NUMBER]`) and bleeped from audio recordings after the conversation ends.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_redaction: Option<bool>,
    /// The speech-to-speech model to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The audio speed of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub audio_speed: Option<f64>,
    /// The background noise type. Can be "office", "call-center", "coffee-shop", or null.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background_noise: Option<OutboundCallConfigBackgroundNoise>,
    /// The background noise level of the agent.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub background_noise_level: Option<f64>,
    /// Array of MCP server names to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mcp_servers: Option<Vec<String>>,
    /// Array of task objects with `name` and `description` fields.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<Task>>,
    /// Pool of phone numbers used for outbound calls.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outbound_number_pool: Option<OutboundNumberPool>,
    /// When `true`, the assistant will produce backchannel responses (e.g. "mm-hmm") while the user is speaking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_assistant_backchannel: Option<bool>,
    /// How aggressively the assistant produces backchannel responses. Only relevant when `enable_assistant_backchannel` is `true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(with = "crate::core::number_serializers::option")]
    pub assistant_backchannel_aggressiveness: Option<f64>,
    /// When not `null`, at the beginning of the conversation the agent will make a POST request to this endpoint to get configuration options.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub configuration_endpoint: Option<OutboundCallConfigConfigurationEndpoint>,
    /// Controls how long transcripts and audio recordings are retained before deletion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data_retention_policy: Option<DataRetentionPolicy>,
}

impl OutboundCallConfig {
    pub fn builder() -> OutboundCallConfigBuilder {
        <OutboundCallConfigBuilder as Default>::default()
    }
}

#[derive(Clone, PartialEq, Default, Debug)]
#[non_exhaustive]
pub struct OutboundCallConfigBuilder {
    agent: Option<String>,
    project: Option<String>,
    generate_welcome_message: Option<bool>,
    is_welcome_message_interruptible: Option<bool>,
    welcome_message: Option<String>,
    system_prompt: Option<String>,
    template_variables: Option<HashMap<String, String>>,
    voice_id: Option<String>,
    generate_no_input_poke_text: Option<bool>,
    no_input_poke_sec: Option<i64>,
    no_input_poke_text: Option<String>,
    no_input_end_conversation_sec: Option<i64>,
    default_language: Option<LanguageCode>,
    additional_languages: Option<Vec<LanguageCode>>,
    languages: Option<Vec<LanguageCode>>,
    multilingual_mode: Option<OutboundCallConfigMultilingualMode>,
    push_to_talk: Option<bool>,
    intelligence_level: Option<OutboundCallConfigIntelligenceLevel>,
    boosted_keywords: Option<Vec<String>>,
    pronunciation_dictionary: Option<Vec<OutboundCallConfigPronunciationDictionaryItem>>,
    min_words_to_interrupt: Option<i64>,
    tools: Option<Vec<OutboundCallConfigToolsItem>>,
    enable_redaction: Option<bool>,
    model: Option<String>,
    audio_speed: Option<f64>,
    background_noise: Option<OutboundCallConfigBackgroundNoise>,
    background_noise_level: Option<f64>,
    mcp_servers: Option<Vec<String>>,
    tasks: Option<Vec<Task>>,
    outbound_number_pool: Option<OutboundNumberPool>,
    enable_assistant_backchannel: Option<bool>,
    assistant_backchannel_aggressiveness: Option<f64>,
    configuration_endpoint: Option<OutboundCallConfigConfigurationEndpoint>,
    data_retention_policy: Option<DataRetentionPolicy>,
}

impl OutboundCallConfigBuilder {
    pub fn agent(mut self, value: impl Into<String>) -> Self {
        self.agent = Some(value.into());
        self
    }

    pub fn project(mut self, value: impl Into<String>) -> Self {
        self.project = Some(value.into());
        self
    }

    pub fn generate_welcome_message(mut self, value: bool) -> Self {
        self.generate_welcome_message = Some(value);
        self
    }

    pub fn is_welcome_message_interruptible(mut self, value: bool) -> Self {
        self.is_welcome_message_interruptible = Some(value);
        self
    }

    pub fn welcome_message(mut self, value: impl Into<String>) -> Self {
        self.welcome_message = Some(value.into());
        self
    }

    pub fn system_prompt(mut self, value: impl Into<String>) -> Self {
        self.system_prompt = Some(value.into());
        self
    }

    pub fn template_variables(mut self, value: HashMap<String, String>) -> Self {
        self.template_variables = Some(value);
        self
    }

    pub fn voice_id(mut self, value: impl Into<String>) -> Self {
        self.voice_id = Some(value.into());
        self
    }

    pub fn generate_no_input_poke_text(mut self, value: bool) -> Self {
        self.generate_no_input_poke_text = Some(value);
        self
    }

    pub fn no_input_poke_sec(mut self, value: i64) -> Self {
        self.no_input_poke_sec = Some(value);
        self
    }

    pub fn no_input_poke_text(mut self, value: impl Into<String>) -> Self {
        self.no_input_poke_text = Some(value.into());
        self
    }

    pub fn no_input_end_conversation_sec(mut self, value: i64) -> Self {
        self.no_input_end_conversation_sec = Some(value);
        self
    }

    pub fn default_language(mut self, value: LanguageCode) -> Self {
        self.default_language = Some(value);
        self
    }

    pub fn additional_languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.additional_languages = Some(value);
        self
    }

    pub fn languages(mut self, value: Vec<LanguageCode>) -> Self {
        self.languages = Some(value);
        self
    }

    pub fn multilingual_mode(mut self, value: OutboundCallConfigMultilingualMode) -> Self {
        self.multilingual_mode = Some(value);
        self
    }

    pub fn push_to_talk(mut self, value: bool) -> Self {
        self.push_to_talk = Some(value);
        self
    }

    pub fn intelligence_level(mut self, value: OutboundCallConfigIntelligenceLevel) -> Self {
        self.intelligence_level = Some(value);
        self
    }

    pub fn boosted_keywords(mut self, value: Vec<String>) -> Self {
        self.boosted_keywords = Some(value);
        self
    }

    pub fn pronunciation_dictionary(mut self, value: Vec<OutboundCallConfigPronunciationDictionaryItem>) -> Self {
        self.pronunciation_dictionary = Some(value);
        self
    }

    pub fn min_words_to_interrupt(mut self, value: i64) -> Self {
        self.min_words_to_interrupt = Some(value);
        self
    }

    pub fn tools(mut self, value: Vec<OutboundCallConfigToolsItem>) -> Self {
        self.tools = Some(value);
        self
    }

    pub fn enable_redaction(mut self, value: bool) -> Self {
        self.enable_redaction = Some(value);
        self
    }

    pub fn model(mut self, value: impl Into<String>) -> Self {
        self.model = Some(value.into());
        self
    }

    pub fn audio_speed(mut self, value: f64) -> Self {
        self.audio_speed = Some(value);
        self
    }

    pub fn background_noise(mut self, value: OutboundCallConfigBackgroundNoise) -> Self {
        self.background_noise = Some(value);
        self
    }

    pub fn background_noise_level(mut self, value: f64) -> Self {
        self.background_noise_level = Some(value);
        self
    }

    pub fn mcp_servers(mut self, value: Vec<String>) -> Self {
        self.mcp_servers = Some(value);
        self
    }

    pub fn tasks(mut self, value: Vec<Task>) -> Self {
        self.tasks = Some(value);
        self
    }

    pub fn outbound_number_pool(mut self, value: OutboundNumberPool) -> Self {
        self.outbound_number_pool = Some(value);
        self
    }

    pub fn enable_assistant_backchannel(mut self, value: bool) -> Self {
        self.enable_assistant_backchannel = Some(value);
        self
    }

    pub fn assistant_backchannel_aggressiveness(mut self, value: f64) -> Self {
        self.assistant_backchannel_aggressiveness = Some(value);
        self
    }

    pub fn configuration_endpoint(mut self, value: OutboundCallConfigConfigurationEndpoint) -> Self {
        self.configuration_endpoint = Some(value);
        self
    }

    pub fn data_retention_policy(mut self, value: DataRetentionPolicy) -> Self {
        self.data_retention_policy = Some(value);
        self
    }

    /// Consumes the builder and constructs a [`OutboundCallConfig`].
    pub fn build(self) -> Result<OutboundCallConfig, BuildError> {
        Ok(OutboundCallConfig {
            agent: self.agent,
            project: self.project,
            generate_welcome_message: self.generate_welcome_message,
            is_welcome_message_interruptible: self.is_welcome_message_interruptible,
            welcome_message: self.welcome_message,
            system_prompt: self.system_prompt,
            template_variables: self.template_variables,
            voice_id: self.voice_id,
            generate_no_input_poke_text: self.generate_no_input_poke_text,
            no_input_poke_sec: self.no_input_poke_sec,
            no_input_poke_text: self.no_input_poke_text,
            no_input_end_conversation_sec: self.no_input_end_conversation_sec,
            default_language: self.default_language,
            additional_languages: self.additional_languages,
            languages: self.languages,
            multilingual_mode: self.multilingual_mode,
            push_to_talk: self.push_to_talk,
            intelligence_level: self.intelligence_level,
            boosted_keywords: self.boosted_keywords,
            pronunciation_dictionary: self.pronunciation_dictionary,
            min_words_to_interrupt: self.min_words_to_interrupt,
            tools: self.tools,
            enable_redaction: self.enable_redaction,
            model: self.model,
            audio_speed: self.audio_speed,
            background_noise: self.background_noise,
            background_noise_level: self.background_noise_level,
            mcp_servers: self.mcp_servers,
            tasks: self.tasks,
            outbound_number_pool: self.outbound_number_pool,
            enable_assistant_backchannel: self.enable_assistant_backchannel,
            assistant_backchannel_aggressiveness: self.assistant_backchannel_aggressiveness,
            configuration_endpoint: self.configuration_endpoint,
            data_retention_policy: self.data_retention_policy,
        })
    }
}
